bread.carpbread.nema=???
bread.carpbread.price=2000
beverage.milk.name=????
beverage.mike.price=15000
beverage.mike.capacity=500
beverage.water.name=??????
beverage.water.price=3000
beverage.water.capacity=500