import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/component/Layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Layout>
          {children}    {/** 라우팅으로 결정된 현재 페이지가 렌더링 되는 자리 */}
        </Layout>
      </body>
    </html>
  );
}
