
import ReduxProvider from "@/components/ReduxProvider";
import Header from '../components/commons/Header';
import Navbar from '../components/commons/Navbar';
import './globals.css';

//   metadata 객체를 export 하면 브라우저 탭에 표시될 제목 등을 설정할 수 있습니다. (SEO에 중요!)
export const metadata = {
  title: 'My Awesome Restaurant App',
  description: 'Generated by Next.js',
}

//   컴포넌트 이름은 RootLayout 등 자유롭게 지을 수 있습니다.
//   가장 중요한 것! props로 'children'을 받습니다.
export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body>
      {/* Redux를 사용하려면, 여기서 Provider로 감싸줘야
                     우리 앱의 모든 클라이언트 컴포넌트가 Store에 접근할 수 있습니다. */}
      <ReduxProvider>
        <div>
          {/* Header와 Navbar는 모든 페이지에 공통으로 보이므로 여기에 위치합니다. */}
          <Header/>
          <Navbar/>
          {/* 현재 URL에 맞는 page.js의 내용이 {children} 자리에 렌더링됩니다. */}
          <main>
            {children}
          </main>
          {/* 여기에 Footer 컴포넌트 등을 추가할 수도 있겠죠. */}
        </div>
      </ReduxProvider>
      </body>
      </html>
  );
}